name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.4'  # Updated to Ruby 3.1.x
        bundler-cache: true

    - name: Fix Dependencies
      run: |
        bundle config set --local path 'vendor/bundle'
        bundle install

    - name: Install Mermaid CLI (for diagrams)
      run: |
        npm install -g mermaid.cli

    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then
          echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
          echo "NO_PUSH=--no-push" >> $GITHUB_OUTPUT
        elif [[ ${GITHUB_REF} = refs/heads/* ]]; then
          echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        fi
        echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_OUTPUT

    - name: Build Jekyll site
      run: |
        JEKYLL_ENV=production bundle exec jekyll build

    - name: Deploy website
      run: |
        yes | bash bin/deploy --verbose ${{ steps.setup.outputs.NO_PUSH }} \
                    --src ${{ steps.setup.outputs.SRC_BRANCH }} \
                    --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}
